Eliminate dependency on mtl
UnkindPartition/tasty pull request #335
Opened 2022-05-09 19:49 UTC by Bodigrim

As suggested at https://github.com/UnkindPartition/tasty/pull/334#issuecomment-1120489902
This will allow `mtl` to have a test suite itself, without a circular dependency.

2022-05-09 21:12 UTC, andreasabel requested changes

2022-05-09 21:12 UTC, andreasabel commented on core/Test/Tasty/Run.hs
> +        tests' = map (first (. ((Seq.|> ini) *** (fin Seq.<|)))) tests
Please make this more pointfull.  This is impossible to comprehend.

2022-05-09 21:12 UTC, andreasabel commented on core/Test/Tasty/Patterns/Eval.hs
> +        Nothing -> lift $ Left $ "Not a number: " ++ show s
Please define a `throwError` for monad `M` and use this here.

2022-05-09 21:12 UTC, andreasabel commented on core/Test/Tasty/Run.hs
> +              Traversal $ (mapWriterT . local) (first (Seq.|> name)) a
A more pointfull style please, to preserve code readability.

2022-05-09 22:09 UTC, Bodigrim commented
@andreasabel done.

2022-05-10 05:36 UTC, andreasabel approved these changes

2022-05-10 12:50 UTC, andreasabel commented
Candidate at: https://hackage.haskell.org/package/tasty-1.4.2.3/candidate

2022-05-10 13:44 UTC, merged