Update changelog
UnkindPartition/tasty pull request #360
Opened 2022-12-17 14:56 UTC by Bodigrim

This is in preparation for `tasty-1.4.3` (#355) release.

2022-12-17 17:08 UTC, andreasabel commented on core/CHANGELOG.md
> +* Drop `wcwidth` dependency.
Please add a "Tested with" GHC version range here.

2022-12-17 17:10 UTC, andreasabel commented on core/CHANGELOG.md
> +* Drop `clock` dependency, decomission `clock` flag.
If this has an issue, please link to it.

2022-12-17 17:11 UTC, andreasabel requested changes
Thanks, LG, with some suggestions.

2022-12-17 18:02 UTC, Bodigrim commented
@andreasabel updated.

2022-12-18 20:42 UTC, Bodigrim commented
@andreasabel I believe I fixed your remarks, so I'll go ahead with a merge to match the proposed date for 1.4.3 release. Happy to make further amends later if you get more suggestions.

2022-12-18 20:42 UTC, merged